export const keywordGroupOptions: {
  label: string
  value: string
  keywords: string[]
}[] = [
  {
    label: '刷分套',
    value: 'shuafen',
    keywords: [
      'mini游戏机',
      '冠军之王',
      'lua简约玩伴装',
      '精灵sara',
      '精灵kuma',
      '智慧头型',
      '冠军之王',
      'ac达人',
      'pd之王',
    ],
  },
  {
    label: '日用品',
    value: 'riyongpin',
    keywords: [
      '昵称卡',
      '名片卡',
      '彩笔',
      '舞蹈',
      '玩伴恰恰舞',
      '玩伴动作',
      '登场特效',
      '聊天框',
      '快乐如风',
      'summer',
      '做游戏',
      '骑马舞',
      '梦想喷雾器',
      '我要抱抱',
      '卡布奇诺',
      '热恋红唇',
      '七彩童话',
      '囧rz',
      '七彩童话',
      '背景框',
      '意念丛林',
      '心心相应',
      '死神印记',
      '舞者为王',
      '梦蝶翩舞',
      '浮云点点',
      '音频闪耀',
      '角色框',
      '胡子',
      '眉目传情',
      '悠悠四叶',
      '魔法奇迹',
      '好奇心少',
      '温和小猫',
    ],
  },
  {
    label: '音速石',
    value: 'yinsushi',
    keywords: ['音速石'],
  },
  {
    label: '模式',
    value: 'moshi',
    keywords: ['突发模式', '镜子模式', '随机模式'],
  },
  {
    label: '铃铛',
    value: 'lingdang',
    keywords: ['金铃铛'],
  },
  {
    label: '永久',
    value: 'yongjiu',
    keywords: ['（永久）'],
  },
]
