/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumModal: typeof import('./src/components/AlbumModal.vue')['default']
    Announcement: typeof import('./src/components/Announcement.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    CustomTitleBar: typeof import('./src/components/CustomTitleBar.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GamePreview: typeof import('./src/components/GamePreview.vue')['default']
    LaunchButton: typeof import('./src/components/LaunchButton.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PakModal: typeof import('./src/components/PakModal.vue')['default']
    ServerStatusDialog: typeof import('./src/components/ServerStatusDialog.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Transfer: typeof import('./src/components/Transfer.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    VersionCheck: typeof import('./src/components/VersionCheck.vue')['default']
    WindowResizer: typeof import('./src/components/WindowResizer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
